server:
  port: 8080
  ssl:
    enabled: true
    key-alias: gateway
    key-store-password: pass
    key-store: classpath:server.p12
    key-store-type: PKCS12

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://zipkin:9411/
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dissertationuaa.eu.auth0.com/
  cloud:
    gateway:
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: dbapp
          uri: lb://dbapp
          predicates:
            - Path=/iot/**
          filters:
            - StripPrefix=1
            - CircuitBreaker=dbapp

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://registry:8761/eureka
    healthcheck:
      enabled: true
