spring:
  application:
    name: mqttclient

mqtt:
  broker:
    uri: ssl://193.122.11.148:8884

auth0:
  issuer: "https://dissertationuaa.eu.auth0.com/"
  client-id: GtkkdbPE9BFlTPiI5wRNFTSQ3z3DhYqT
  audience: secureiot
  grant-type: client_credentials

vault:
  uri: https://193.122.11.148:8200/
  token: ${WRAPPING_TOKEN}

gw:
  uri: https://193.122.11.148:8080
